### ISSUE TITLE
Cannot make project on ovr_sdk_mobile 1.7

### ISSUE THREAD

**Issue by felislynx-silae** [Samsung/GearVRf#1430]
I've got those errors while trying to make framework from master branch.

GearVRf/GVRf/Framework/backend_oculus/src/main/jni/ovr_activity.cpp
Error:(72) undefined reference to 'vrapi_ShowFatalError'
Error:(94) undefined reference to 'vrapi_ShowSystemUI'
GearVRf/GVRf/Framework/backend_oculus/src/main/jni/ovr_gear_controller.cpp
Error:(27) undefined reference to 'vrapi_EnumerateInputDevices'
Error:(59) undefined reference to 'vrapi_GetInputDeviceCapabilities'
Error:(67) undefined reference to 'vrapi_GetCurrentInputState'
Error:(69) undefined reference to 'vrapi_RecenterInputPose'
Error:(84) undefined reference to 'vrapi_GetInputTrackingState'
Error:(96) undefined reference to 'vrapi_GetCurrentInputState'

**Comment by liaxim** [comment]
@felislynx-silae Hi. Which version of the Oculus Mobile SDK are you using? 1.5.0 or 1.7.0 are required for the master branch.

**Comment by liaxim** [comment]
@felislynx-silae Sorry. It is in the title. Check you build log for this message: "OVR_MOBILE_SDK is set to ...". Please verify the build is using the correct OVR_MOBILE_SDK value.

**Comment by felislynx-silae** [comment]
/home/lynx/Workspaces/Libs/ovr_sdk_mobile_1.7

**Comment by liaxim** [comment]
@felislynx-silae We have couple of people here that build with 1.7.0. It definitely works for us . Is it possible that your installation is somehow messed up?

**Comment by felislynx-silae** [comment]
@liaxim so i'm on Antergos Linux.
Framework is latest master
OVR_MOBILE_SDK is downloaded from oculus website and extracted to location above.
JDK 1.8.0.144.
I'm openig framework project in Android Studio and then Build -> Make project and errors above show up, i'f i'll change path to OVR then other errors shows up.

**Comment by liaxim** [comment]
What happens if you add ``#include "VrApi_Input.h"`` to the includes section of ovr_activity.cpp?

**Comment by liaxim** [comment]
Does ``VrApi/Include/VrApi_Input.h`` exist in your installation? Are the missing methods declared in it?

**Comment by felislynx-silae** [comment]
```
/************************************************************************************

Filename    :   VrApi_Input.h
Content     :   Input API
Created     :   Feb 9, 2016
Authors     :   Jonathan E. Wright
Language    :   C99

Copyright   :   Copyright 2015 Oculus VR, LLC. All Rights reserved.

*************************************************************************************/
#ifndef OVR_VrApi_Input_h
#define OVR_VrApi_Input_h


#include <stddef.h>
#include <stdint.h>
#include "VrApi_Config.h"
#include "VrApi_Types.h"

// Describes button input types.
// For the Gear VR Controller and headset, only the following ovrButton types are reported to the application:
//
// ovrButton_Back, ovrButton_A, ovrButton_Enter
//
// ovrButton_Home, ovrButton_VolUp, ovrButtonVolDown and ovrButton_Back are system buttons that are never
// reported to applications.
// ovrButton_Back button has system-level handling for long presses, but application-level handling for 
// short-presses. Since a short-press is determined by the time interval between down and up events, the
// ovrButton_Back flag is only set when the back button comes up in less than the short-press time (0.25
// seconds). The ovrButton_Back flag always signals a short press and will only remain set for a single frame.

typedef enum ovrButton_
{
	ovrButton_A         = 0x00000001,	// Set for trigger pulled on the Gear VR Controller
	ovrButton_B         = 0x00000002,
	ovrButton_RThumb    = 0x00000004,
	ovrButton_RShoulder = 0x00000008,

	ovrButton_X         = 0x00000100,
	ovrButton_Y         = 0x00000200,
	ovrButton_LThumb    = 0x00000400,
	ovrButton_LShoulder = 0x00000800,

	ovrButton_Up        = 0x00010000,
	ovrButton_Down      = 0x00020000,
	ovrButton_Left      = 0x00040000,
	ovrButton_Right     = 0x00080000,
	ovrButton_Enter     = 0x00100000,	// Set for touchpad click on the Gear VR Controller
	ovrButton_Back      = 0x00200000,	// Back button on the headset or Gear VR Controller (only set when a short press comes up)

	ovrButton_EnumSize  = 0x7fffffff
} ovrButton;

// Specifies which controller is connected; multiple can be connected at once.
typedef enum ovrControllerType_
{
	ovrControllerType_None			= 0,
	ovrControllerType_Reserved0		= ( 1 << 0 ),	// LTouch in CAPI
	ovrControllerType_Reserved1		= ( 1 << 1 ),	// RTouch in CAPI
	ovrControllerType_TrackedRemote	= ( 1 << 2 ),
	ovrControllerType_Headset		= ( 1 << 3 ),
	ovrControllerType_Reserved2		= ( 1 << 4 ),	// Xbox in CAPI

	ovrControllerType_EnumSize		= 0x7fffffff
} ovrControllerType;

typedef uint32_t ovrDeviceID;

typedef enum ovrDeviceIdType_
{
	ovrDeviceIdType_Invalid	= 0x7fffffff
} ovrDeviceIdType;

// This header starts all ovrInputCapabilities structures. It should only hold fields
// that are common to all input controllers.
typedef struct ovrInputCapabilityHeader_
{
	ovrControllerType	Type;

	// A unique ID for the input device
	ovrDeviceID			DeviceID;
} ovrInputCapabilityHeader;

// specifies capabilites of a controller
// Note that left and right hand are non-exclusive (a two-handed controller could set both)
typedef enum ovrControllerCapabilities_
{
	ovrControllerCaps_HasOrientationTracking 	= 0x00000001,
	ovrControllerCaps_HasPositionTracking 		= 0x00000002,
	ovrControllerCaps_LeftHand					= 0x00000004,	// controller is configured for left hand
	ovrControllerCaps_RightHand					= 0x00000008,	// controller is configured for right hand


	ovrControllerCaps_EnumSize 					= 0x7fffffff
} ovrControllerCapabilties;

typedef struct ovrInputTrackedRemoteCapabilities_
{
	ovrInputCapabilityHeader	Header;

	// mask of controller capabilities described by ovrControllerCapabilities
	uint32_t					ControllerCapabilities;

	// mask of button capabilities described by ovrButton
	uint32_t					ButtonCapabilities;

	// Maximum coordinates of the Trackpad, bottom right exclusive
	// For a 300x200 Trackpad, return 299x199
	uint16_t					TrackpadMaxX;
	uint16_t					TrackpadMaxY;

	// Size of the Trackpad in mm (millimeters)
	float						TrackpadSizeX;
	float						TrackpadSizeY;
} ovrInputTrackedRemoteCapabilities;

// Capabilities for the Head Mounted Tracking device (i.e. the headset).
// Note that the GearVR headset firmware always sends relative coordinates 
// with the initial touch position offset by (1280,720). There is no way
// to get purely raw coordinates from the headset. In addition, these 
// coordinates get adjusted for acceleration resulting in a slow movement 
// from one edge to the other the having a coordinate range of about 300 
// units, while a fast movement from edge to edge may result in a range
// close to 900 units.
// This means the headset touchpad needs to be handled differently than 
// the GearVR Controller touchpad.
typedef struct ovrInputHeadsetCapabilities_
{
	ovrInputCapabilityHeader	Header;

	// mask of controller capabilities described by ovrControllerCapabilities
	uint32_t					ControllerCapabilities;

	// mask of button capabilities described by ovrButton
	uint32_t					ButtonCapabilities;

	// Maximum coordinates of the Trackpad, bottom right exclusive
	// For a 300x200 Trackpad, return 299x199
	uint16_t					TrackpadMaxX;
	uint16_t					TrackpadMaxY;

	// Size of the Trackpad in mm (millimeters)
	float						TrackpadSizeX;
	float						TrackpadSizeY;
} ovrInputHeadsetCapabilities;

// This header starts all ovrInputState structures. It should only hold fields
// that are common to all input controllers.
typedef struct ovrInputStateHeader_
{
	// type type of controller
	ovrControllerType 	ControllerType;

	// System time when the controller state was last updated.
	double				TimeInSeconds;
} ovrInputStateHeader;

// ovrInputStateTrackedRemote describes the complete input state for the 
// orientation-tracked remote. The TrackpadPosition coordinates returned 
// for the GearVR Controller are in raw, absolute units.
typedef struct ovrInputStateTrackedRemote_
{
	ovrInputStateHeader Header;

	// Values for buttons described by ovrButton.
	uint32_t	        Buttons;

	// finger contact status for trackpad
	// true = finger is on trackpad, false = finger is off trackpad
	uint32_t            TrackpadStatus;

	// X and Y coordinates of the Trackpad
	ovrVector2f         TrackpadPosition;

	// The percentage of max battery charge remaining.
	uint8_t				BatteryPercentRemaining;	
	// Increments every time the remote is recentered. If this changes, the application may need
	// to adjust its arm model accordingly.
	uint8_t				RecenterCount;				
	// Reserved for future use.
	uint16_t			Reserved;
} ovrInputStateTrackedRemote;

// ovrInputStateHeadset describes the complete input state for the 
// GearVR headset. The TrackpadPosition coordinates return for the
// headset are relative coordinates, centered at (1280,720). See the
// comments on ovrInputHeadsetCapabilities for more information.
typedef struct ovrInputStateHeadset_
{
	ovrInputStateHeader	Header;

	// Values for buttons described by ovrButton.
	uint32_t	        Buttons;

	// finger contact status for trackpad
	// true = finger is on trackpad, false = finger is off trackpad
	uint32_t            TrackpadStatus;

	// X and Y coordinates of the Trackpad
	ovrVector2f         TrackpadPosition;
} ovrInputStateHeadset;

#if defined( __cplusplus )
extern "C" {
#endif

// Enumerates the input devices connected to the system
// Start with index=0 and counting up. Stop when ovrResult is < 0
//
// Input: ovrMobile, device index, and a capabilities header
// The capabilities header does not need to have any fields set before calling.
// Output: capabilitiesHeader with information for that enumeration index
OVR_VRAPI_EXPORT ovrResult vrapi_EnumerateInputDevices( ovrMobile * ovr, const uint32_t index, ovrInputCapabilityHeader * capsHeader );

// Returns the capabilities of the input device for the corresponding device ID
//
// Input: ovr, pointer to a capabilities structure
// Output: capabilities will be filled with information for the deviceID
// Example:
//     The Type field of the capabilitiesHeader must be set when calling this function.
//     Normally the capabilitiesHeader is obtained from the vrapi_EnumerateInputDevices API
//     The Type field in the header should match the structure type that is passed.
//
//         ovrInputCapabilityHeader capsHeader;
//         if ( vrapi_EnumerateInputDevices( ovr, deviceIndex, &capsHeader ) >= 0 ) {
//             if ( capsHeader.Type == ovrDeviceType_TrackedRemote ) {
//                 ovrInputTrackedRemoteCapabilities remoteCaps;
//                 remoteCaps.Header = capsHeader;
//                 vrapi_GetInputDeviceCapabilities( ovr, &remoteCaps.Header );
OVR_VRAPI_EXPORT ovrResult vrapi_GetInputDeviceCapabilities( ovrMobile * ovr, ovrInputCapabilityHeader * capsHeader );

// Returns the current input state for controllers, without positional tracking info.
//
// Input: ovr, deviceID, pointer to a capabilities structure (with Type field set)
// Output: Upon return the inputState structure will be set to the device's current input state
// Example:
//     The Type field of the passed ovrInputStateHeader must be set to the type that
//     corresponds to the type of structure being passed.
//     The pointer to the ovrInputStateHeader should be a pointer to a Header field in
//     structure matching the value of the Type field.
// 
//     ovrInputStateTrackedRemote state;
//     state.Header.Type = ovrControllerType_TrackedRemote;
//     if ( vrapi_GetCurrentInputState( ovr, remoteDeviceID, &state.Header ) >= 0 ) {
OVR_VRAPI_EXPORT ovrResult vrapi_GetCurrentInputState( ovrMobile * ovr, const ovrDeviceID deviceID, ovrInputStateHeader * inputState );

// Returns the predicted input state based on the specified absolute system time
// in seconds. Pass absTime value of 0.0 to request the most recent sensor reading.
// Input: ovr, device ID, prediction time
// Output: ovrTracking structure containing the device's predicted tracking state.
OVR_VRAPI_EXPORT ovrResult vrapi_GetInputTrackingState( ovrMobile * ovr, const ovrDeviceID deviceID, 
														const double absTimeInSeconds, ovrTracking * tracking );

// Can be called from any thread while in VR mode. Recenters the tracked remote to the current yaw of the headset.
// Input: ovr, device ID
// Output: None
OVR_VRAPI_EXPORT void vrapi_RecenterInputPose( ovrMobile * ovr, const ovrDeviceID deviceID );

// Enable or disable emulation for the GearVR Controller. 
// Emulation is on by default.
// If emulationOn == true, then button and touch events on the GearVR Controller will be sent through the Android
// dispatchKeyEvent and dispatchTouchEvent path as if they were from the headset buttons and touchpad.
// Applications that are intentionally enumerating the controller will likely want to turn emulation off in order
// to differentiate between controller and headset input events.
OVR_VRAPI_EXPORT ovrResult vrapi_SetRemoteEmulation( ovrMobile * ovr, const bool emulationOn );

#if defined( __cplusplus )
}   // extern "C"
#endif


#endif	// OVR_VrApi_Input_h


```

```
ovr_activity.cpp

#include "ovr_activity.h"
#include "../util/jni_utils.h"
#include "../eglextension/msaa/msaa.h"
#include "VrApi.h"
#include "VrApi_Helpers.h"
#include "VrApi_SystemUtils.h"
#include <cstring>
#include <unistd.h>
#include <VrApi_Types.h>
#include "engine/renderer/renderer.h"
```

```
ovr_gear_controller.cpp

#include "ovr_gear_controller.h"
#include "VrApi_Input.h"
```

**Comment by liaxim** [comment]
@felislynx-silae Did adding ``#include "VrApi_Input.h"`` to ovr_activity.cpp make any difference? Which NDK version are you using?

**Comment by felislynx-silae** [comment]
Nope, adding this include didn't changed anything. I'm using 15.2.4203891 NDK (latest via Android SDK)

**Comment by felislynx-silae** [comment]
in ovr_activity.cpp -> VrApi_SystemUtils.h is marked as unused (which contains missing methods)
in ovr_gear_controller.cpp -> VrApi_Input.h is missing (which contains missing methods) but adding include doesn't fix anything

**Comment by dnvasilev** [comment]
VrApi_Input.h is already included from ovr_gear_controller.h; it is unused because the first (indirect) include has #define OVR_VrApi_Input_h header guard macro. Please check the exact path to VrApi_Input.h in Android Studio: in ovr_gear_controller.cpp, right click on vrapi_EnumerateInputDevices and "Go To" "Declararation". Check the path to the file that opens.

**Comment by felislynx-silae** [comment]
it went to ovr_sdk_mobile_1.7/VrApi/include/VrApi_input.h

**Comment by dnvasilev** [comment]
@felislynx-silae the next check is to make sure that Android Studio editor and compiler agree on the include file path. Add #error directive to VrApi_input.h and see if compile fails with this exact error.

**Comment by felislynx-silae** [comment]
/home/lynx/Workspaces/Libs/ovr_sdk_mobile_1.7/VrApi/Include/VrApi_Input.h
Error:(20, 2) error: #error 

(#error is in line 20)

**Comment by dnvasilev** [comment]
@felislynx-silae Then the error comes from the linker: it can't find the library, or the build system tries to rebuild library that already exists

**Comment by felislynx-silae** [comment]
I'm unfamiliar with NDK/C++ so it tells me nothing :/
My steps were simple, download framework, set path to ovr_sdk_mobile (latest from web), hit make to build framework, backends and 3dcursor to use latest controller class and errors above shows up

**Comment by dnvasilev** [comment]
Please check if your build.gradle contains the following

`    android {`
`       sourceSets.main {`
`            jni.srcDirs = [] // no auto generation of Android.mk`
`            jniLibs.srcDir 'libs' // pre-compiled libraries`
`        }`
`    }`

**Comment by felislynx-silae** [comment]
@dnvasilev 
sourceSets.main {
        java.srcDirs = ['src/main/java']
        jni.srcDirs = [] // no auto generation of Android.mk
        // pre-compiled libraries
        jniLibs {
            srcDir 'src/main/libs'
        }
    }
It is master branch -> unchanged by me

**Comment by dnvasilev** [comment]
@felislynx-silae Let me get the exact version you use. Looks like you use Linux and Android Studio 2.3.3, and the latest master branch for GearVRf and GearVRf-Demos.

**Comment by felislynx-silae** [comment]
Antergos 64b, NDK was downloaded by Android SDK

**Comment by liaxim** [comment]
@felislynx-silae Is it possible you may have an old version of libvrapi.so checked in somewhere in your libs folder? After ``git clean -fdx`` there should be no libvrapi.so left behind in your repo. The correct so is automatically included by the build.

**Comment by dnvasilev** [comment]
@felislynx-silae  I use ~/.gradle/gradle.properties to set up the environment. Please check if yours is similar:
$ cat ~/.gradle/gradle.properties 
OCULUS_SIGS_DIRECTORY=/home/d.vasilev/Downloads
ANDROID_NDK_HOME=/home/d.vasilev/Android/Sdk/ndk-bundle
ANDROID_HOME=/home/d.vasilev/Android/Sdk
OVR_MOBILE_SDK=/home/d.vasilev/ovr_sdk_mobile_1.7.0
OVR_PLATFORM_SDK=/home/d.vasilev/OculusPlatformSDK1.16.0
useLocalDependencies=true
do_not_package_for_plugins=true

**Comment by felislynx-silae** [comment]
I've checked. For safety setted same values in .gradle/gradle.properties (of course changed paths first :) ). No changes at all

**Comment by felislynx-silae** [comment]
ovr_platform_sdk_1.8 not 1.16.0

**Comment by dnvasilev** [comment]
gvr-3dcursor builds for me in clean repo with or without useLocalDependencies=true.
I use Ubuntu 14.04.1 x86_64 and JDK 1.8.0_91

@felislynx-silae , when you 
> build framework, backends and 3dcursor 

do you build extension GearVRf/GVRf/Extensions/3DCursor, or demo app GearVRf-Demos/gvr-3dcursor ?

**Comment by felislynx-silae** [comment]
everything but backend_oculus is building for me (3DCursor, framework,backend_daydream,platformsdk_support)

**Comment by felislynx-silae** [comment]
Sometimes gradle have artifacts in its cache which allows to build even if something is wrong. I've had project which was building correctly for everyone but devs who checked out it correctly. And it was because gradle had missing/notcorrupted dependency in cache for other devs

**Comment by liaxim** [comment]
@felislynx-silae As @dnvasilev stated, the error is coming from the linker. You are likely linking to older version of libvrapi.so.

Run the following from your GVRf folder: `` file `find . -name libvrapi.so` ``
Do all matches show this build id: ``BuildID[sha1]=cb3ddd36e10bd6f8a9780d378e2873005ff01616``?

**Comment by dnvasilev** [comment]
@felislynx-silae Before building from scratch, I usually do the following:
Close projects in Android Studio
Close Android Studio
cd ../GearVRf; git clean -dxf
cd ../GearVRf-Demos; git clean -dxf
rm -rf ~/.gradle/caches

**Comment by felislynx-silae** [comment]
GearVRf/GVRf/Framework opened by android studio is able to build daydream backend and framework but not oculus_backend. Same issue on other pc with Windows 10 (just checked)

**Comment by dnvasilev** [comment]
@felislynx-silae 
Here's the exact build steps after cleanup:
Open GearVRf/GVRf/Framework project. Gradle Plugin: Don't remind again.
Sync Project with Gradle Files
Make Module 'framework'
Make Module 'backenddaydream'
Make Module 'backendoculus'
Open GearVRf/GVRf/Extensions project in a new Window. Gradle Plugin: Don't remind again.
Sync Project with Gradle Files
Make Project
Open GearVRf-Demos/gvr-3dcursor project in a new Window. Gradle Plugin: Don't remind again.
Sync Project with Gradle Files
Make Project
Build APK
Run 'app'

**Comment by felislynx-silae** [comment]
Ok, so 3rd "make" causes all the issues. Is there any place with ovr_mobile_sdk 1.5? I've searched oculus website but only 1.7 is available (maybe this is an issue?)

**Comment by liaxim** [comment]
https://developer.oculus.com/downloads/package/oculus-mobile-sdk/1.5.0/. You can click the "1.7.0" from the default web page to select the version.

**Comment by dnvasilev** [comment]
@felislynx-silae : is it Androind Studio problem or Gradle build problem? Try:
cd GearVRf/GVRf/Framework
./gradlew :backend_oculus:compileDebugSources

**Comment by felislynx-silae** [comment]
Too late, first command is in progress (on veeery slow network right now)

**Comment by felislynx-silae** [comment]
```
OVR_MOBILE_SDK is set to /home/lynx/Workspaces/Libs/ovr_sdk_mobile_1.7
  Android NDK: WARNING:/home/lynx/Workspaces/Libs/GearVRf/GVRf/Framework/backend_oculus/src/main/jni/Android.mk:gvrf-oculus: non-system libraries in linker flags: /home/lynx/Workspaces/Libs/GearVRf/GVRf/Framework/backend_oculus/../framework/build/intermediates/ndkBuild/debug/obj/local/armeabi-v7a/libgvrf.so    
  Android NDK:     This is likely to result in incorrect builds. Try using LOCAL_STATIC_LIBRARIES    
  Android NDK:     or LOCAL_SHARED_LIBRARIES instead to list the library dependencies of the    
  Android NDK:     current module    
  [armeabi-v7a] Compile++ arm  : gvrf-oculus <= buildinfo.cpp
  [armeabi-v7a] SharedLibrary  : libgvrf-oculus.so
  /home/lynx/Workspaces/Libs/GearVRf/GVRf/Framework/backend_oculus/src/main/jni/ovr_activity.cpp:72: error: undefined reference to 'vrapi_ShowFatalError'
  /home/lynx/Workspaces/Libs/GearVRf/GVRf/Framework/backend_oculus/src/main/jni/ovr_activity.cpp:94: error: undefined reference to 'vrapi_ShowSystemUI'
  /home/lynx/Workspaces/Libs/GearVRf/GVRf/Framework/backend_oculus/src/main/jni/ovr_gear_controller.cpp:27: error: undefined reference to 'vrapi_EnumerateInputDevices'
  /home/lynx/Workspaces/Libs/GearVRf/GVRf/Framework/backend_oculus/src/main/jni/ovr_gear_controller.cpp:59: error: undefined reference to 'vrapi_GetInputDeviceCapabilities'
  /home/lynx/Workspaces/Libs/GearVRf/GVRf/Framework/backend_oculus/src/main/jni/ovr_gear_controller.cpp:67: error: undefined reference to 'vrapi_GetCurrentInputState'
  /home/lynx/Workspaces/Libs/GearVRf/GVRf/Framework/backend_oculus/src/main/jni/ovr_gear_controller.cpp:69: error: undefined reference to 'vrapi_RecenterInputPose'
  /home/lynx/Workspaces/Libs/GearVRf/GVRf/Framework/backend_oculus/src/main/jni/ovr_gear_controller.cpp:84: error: undefined reference to 'vrapi_GetInputTrackingState'
  /home/lynx/Workspaces/Libs/GearVRf/GVRf/Framework/backend_oculus/src/main/jni/ovr_gear_controller.cpp:96: error: undefined reference to 'vrapi_GetCurrentInputState'
  collect2: error: ld returned 1 exit status
  make: *** [/home/lynx/Workspaces/Libs/GearVRf/GVRf/Framework/backend_oculus/build/intermediates/ndkBuild/debug/obj/local/armeabi-v7a/libgvrf-oculus.so] Error 1


* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

```

**Comment by felislynx-silae** [comment]
1.5, same errors o_O

**Comment by dnvasilev** [comment]
@felislynx-silae Just in case, check if git working tree is clean
$ git status
On branch master
Your branch is up-to-date with 'upstream/master'.
nothing to commit, working tree clean

**Comment by dnvasilev** [comment]
@felislynx-silae There's an option to print all build commands Gradle generates:

cd GearVRf/GVRf/Framework
V=1 ./gradlew :backend_oculus:assembleDebug

I am looking for this:

[armeabi-v7a] SharedLibrary  : libgvrf-oculus.so
/home/d.vasilev/Android/Sdk/ndk-bundle/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/arm-linux-androideabi-g++ -Wl,-soname,libgvrf-oculus.so -shared --sysroot=/home/d.vasilev/Android/Sdk/ndk-bundle/platforms/android-21/arch-arm /home/d.vasilev/GVRFCurrent4/GearVRf/GVRf/Framework/backend_oculus/build/intermediates/ndkBuild/release/obj/local/armeabi-v7a/objs/gvrf-oculus/buildinfo.o /home/d.vasilev/GVRFCurrent4/GearVRf/GVRf/Framework/backend_oculus/build/intermediates/ndkBuild/release/obj/local/armeabi-v7a/objs/gvrf-oculus/ovr_activity.o /home/d.vasilev/GVRFCurrent4/GearVRf/GVRf/Framework/backend_oculus/build/intermediates/ndkBuild/release/obj/local/armeabi-v7a/objs/gvrf-oculus/ovr_activity_jni.o /home/d.vasilev/GVRFCurrent4/GearVRf/GVRf/Framework/backend_oculus/build/intermediates/ndkBuild/release/obj/local/armeabi-v7a/objs/gvrf-oculus/ovr_framebufferobject.o /home/d.vasilev/GVRFCurrent4/GearVRf/GVRf/Framework/backend_oculus/build/intermediates/ndkBuild/release/obj/local/armeabi-v7a/objs/gvrf-oculus/ovr_gear_controller.o /home/d.vasilev/GVRFCurrent4/GearVRf/GVRf/Framework/backend_oculus/build/intermediates/ndkBuild/release/obj/local/armeabi-v7a/objs/gvrf-oculus/ovr_gear_controller_jni.o /home/d.vasilev/GVRFCurrent4/GearVRf/GVRf/Framework/backend_oculus/build/intermediates/ndkBuild/release/obj/local/armeabi-v7a/objs/gvrf-oculus/util/ovr_configuration_helper.o /home/d.vasilev/GVRFCurrent4/GearVRf/GVRf/Framework/backend_oculus/build/intermediates/ndkBuild/release/obj/local/armeabi-v7a/objs/gvrf-oculus/monoscopic/monoscopic_renderer_jni.o /home/d.vasilev/Android/Sdk/ndk-bundle/sources/cxx-stl/gnu-libstdc++/4.9/libs/armeabi-v7a/libgnustl_static.a -lgcc -Wl,--exclude-libs,libgcc.a /home/d.vasilev/GVRFCurrent4/GearVRf/GVRf/Framework/backend_oculus/build/intermediates/ndkBuild/release/obj/local/armeabi-v7a/libvrapi.so -no-canonical-prefixes -march=armv7-a -Wl,--fix-cortex-a8   -Wl,--build-id -Wl,--no-undefined -Wl,-z,noexecstack -Wl,-z,relro -Wl,-z,now -Wl,--warn-shared-textrel -Wl,--fatal-warnings   -L/home/d.vasilev/Android/Sdk/ndk-bundle/platforms/android-21/arch-arm/usr/lib -ljnigraphics -llog -lGLESv3 -lEGL -lz -landroid /home/d.vasilev/GVRFCurrent4/GearVRf/GVRf/Framework/backend_oculus/../framework/build/intermediates/ndkBuild/release/obj/local/armeabi-v7a/libgvrf.so -lc -lm -o /home/d.vasilev/GVRFCurrent4/GearVRf/GVRf/Framework/backend_oculus/build/intermediates/ndkBuild/release/obj/local/armeabi-v7a/libgvrf-oculus.so

**Comment by felislynx-silae** [comment]
Success, i've successfully built backend_oculus. i've purged every cache, every build folder and it make it work.
After copyying debug.aars into gvr-controller demo and launching it:
java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "_ZN3gvr9CameraRig14updateRotationEv" referenced by "/data/app/pl.fream.test.gearvr-1/lib/arm/libgvrf-oculus.so"...

It means that my build is still "wrong" or something else?

**Comment by liaxim** [comment]
@felislynx-silae To make the demos use your local aars you need to:
1. set the useLocalDependencies gradle property to true
2. have the GearVRf and the GearVRf-Demos reside in the same directory; the demo build will pick up the aars from GearVRf/GVRf/gearvrf-libs/.

And yes, there is something in your environment that is off. I wish we knew the root cause of your problem so we can document or do something about it.

**Comment by felislynx-silae** [comment]
I'm copying demo to another location, use normal gradle file which is pointing to aar's in this demo folder (to make sure, that i'm separated from other dependencies) (path is gvr-controllerLocal/app/libs).

**Comment by liaxim** [comment]
If you keep having trouble it might be helpful if you try to use the snapshots. They were updated today.

For reference: https://github.com/gearvrf/GearVRf-Demos/blob/master/template/GVRFApplication/app/build.gradle

**Comment by liaxim** [comment]
@felislynx-silae Are you still having problems?

**Comment by felislynx-silae** [comment]
This weekend i'll try snapshots. Local build of all aar's is ok (so original problem is solved) but those aars are generating this crash
java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "_ZN3gvr9CameraRig14updateRotationEv" referenced by "/data/app/pl.fream.test.gearvr-1/lib/arm/libgvrf-oculus.so"...

**Comment by felislynx-silae** [comment]
Your snapshots are working. I'm still wondering why my builds are crashing. It would be helpfull to be able to build master instead of waiting for snapshot or release :). If you'll have time in future i would be glad to resolve this (and maybe describe it for FAQ)

**Comment by liaxim** [comment]
To have a chance of catching what is different when you build we will need this:

1. ``git clean -fdx`` your GearVRf repo
2. Build with ``./gradlew -i -d assembleDebug`` and sends us the build log
3. Send us the ``framework-debug.aar`` and ``backend_oculus-debug.aar`` from GearVRf/GVRf/gearvrf-libs/

**Comment by liaxim** [comment]
@felislynx-silae Can we close this issue or do you planning sending us logs? Thanks.

**Comment by felislynx-silae** [comment]
@liaxim will do. Since that day i'm working on release of app on oculus store (1.0 version!) :) which is very time consuming. Because of that we moved gearvrf upgrade in time. I've hoped to finish release faster but i've got report of failed test which me and my team cannot reproduce :) so, it'll take time. Will do it as soon as i'll close app release
